In [1]:
s='hello'
print(s)

hello


In [2]:
!pip install numpy

In [3]:
import numpy as np
ages=[34,56,75]
ages

[34, 56, 75]

In [5]:
arr=np.array(ages)
arr

array([34, 56, 75])

In [6]:
arr[2]

75

In [7]:
arr[-3]

34

In [8]:
arr1=([[10,20,30],[40,50,60]])
arr1

[[10, 20, 30], [40, 50, 60]]

In [9]:
arr1[0]

[10, 20, 30]

In [10]:
arr1[0][2] #first bracket-row second bracket- column

30

In [11]:
arr.dtype

dtype('int32')

In [13]:
arr=np.array(ages,dtype='float')
arr

array([34., 56., 75.])

In [17]:
#explicit type casting string>float etc etc
marks=[50,60,70,80.90]
marks

[50, 60, 70, 80.9]

In [18]:
np.array(marks)

array([50. , 60. , 70. , 80.9])

In [20]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
list(range(5,15,2))

[5, 7, 9, 11, 13]

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.full([3,4],6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [34]:
np.linspace(4,16,10)

array([ 4.        ,  5.33333333,  6.66666667,  8.        ,  9.33333333,
       10.66666667, 12.        , 13.33333333, 14.66666667, 16.        ])

In [36]:
np.linspace(5,15,6) #linspace function give equal difference between the numbers

array([ 5.,  7.,  9., 11., 13., 15.])

In [43]:
arr7=np.random.randint(5,50,16)
arr7

array([34, 10, 23, 26, 13,  7, 41,  8, 31, 29, 21, 45,  5, 44, 18,  6])

In [48]:
arr3=arr7.reshape([4,4])
arr3

array([[34, 10, 23, 26],
       [13,  7, 41,  8],
       [31, 29, 21, 45],
       [ 5, 44, 18,  6]])

In [50]:
arr3.ndim

2

In [52]:
arr3.shape

(4, 4)

In [54]:
arr3.size

16

In [1]:
l1=[100,200,300,400,500]
l1

[100, 200, 300, 400, 500]

In [2]:
l2=[10,20,30,40,50]
l2

[10, 20, 30, 40, 50]

In [3]:
l1+l2 #the add operator in list will concat the lists

[100, 200, 300, 400, 500, 10, 20, 30, 40, 50]

In [7]:
import numpy as np
array1=np.array(l1)
array1

array([100, 200, 300, 400, 500])

In [8]:
array2=np.array(l2)
l2

[10, 20, 30, 40, 50]

In [9]:
array1+array2 #on arrays any mathematical operations are possible

array([110, 220, 330, 440, 550])

In [10]:
array1-array2

array([ 90, 180, 270, 360, 450])

In [11]:
#mathematical calculations are not possible for arrays of different sizes


In [12]:
np.mean(array1)

300.0

In [13]:
np.median(array2)

30.0

In [14]:
np.mode(array1) #mode and count function is not available

AttributeError: module 'numpy' has no attribute 'mode'

In [17]:
arr=np.random.randint(25,75,12)
arr

array([37, 28, 47, 70, 50, 49, 43, 53, 42, 34, 65, 38])

In [18]:
arr[arr>50] #conditional indexing

array([70, 53, 65])

In [19]:
arr[(arr>40) & (arr<60)] #arr[() & ()]

array([47, 50, 49, 43, 53, 42])

In [29]:
x=20
y=x
x

20

In [30]:
y

20

In [31]:
y=30
y

30

# shallow copy(resize) and deep copy(reshape)

In [36]:
arr_reshaped=np.reshape(arr,(3,4))
arr_reshaped

array([[37, 28, 47, 70],
       [50, 49, 43, 53],
       [42, 34, 65, 38]])

In [34]:
arr_resized=np.resize(arr,(3,4))
arr_resized

array([[37, 28, 47, 70],
       [50, 49, 43, 53],
       [42, 34, 65, 38]])

In [37]:
arr_reshaped[1,2]=600 
arr_reshaped

array([[ 37,  28,  47,  70],
       [ 50,  49, 600,  53],
       [ 42,  34,  65,  38]])

In [40]:
arr_resized[0,3]=700
arr_resized

array([[ 37,  28,  47, 700],
       [ 50,  49,  43,  53],
       [ 42,  34,  65,  38]])

In [41]:
np.sum(arr_reshaped)

1113

In [42]:
np.sum(arr_reshaped,axis=0) #0 for columns

array([129, 111, 712, 161])

In [44]:
np.sum(arr_resized,axis=1) #1 for rows

array([812, 195, 179])

In [45]:
np.mean(arr_reshaped,axis=0)

array([ 43.        ,  37.        , 237.33333333,  53.66666667])

In [46]:
np.median(arr_resized,axis=1)

array([42. , 49.5, 40. ])

In [48]:
arr_flattened=arr_resized.flatten() #deep copy
arr_flattened

array([ 37,  28,  47, 700,  50,  49,  43,  53,  42,  34,  65,  38])

In [50]:
arr_raveled=np.ravel(arr_resized) #shallow copy
arr_raveled

array([ 37,  28,  47, 700,  50,  49,  43,  53,  42,  34,  65,  38])

In [7]:
import pandas as pd
import numpy as np

s=pd.Series([1,2,3,4], index=["a","b","c","d"])
s

a    1
b    2
c    3
d    4
dtype: int64

In [8]:
s["a"]

1

In [9]:
s2=s.reindex(["b","c","d","e","f"])
s2

b    2.0
c    3.0
d    4.0
e    NaN
f    NaN
dtype: float64

In [1]:
import pandas as pd #r is raw string
filepath=r"C:\Users\RDP15\Downloads\diabetes.csv"
diabetes=pd.read_csv(filepath)
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1